//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 12:52:00 PM CET 
//


package eu.apenet.dpt.utils.eaccpf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for cpfRelation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cpfRelation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:isbn:1-931666-33-4}m.relationBody"&gt;
 *       &lt;attribute name="cpfRelationType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="identity"/&gt;
 *             &lt;enumeration value="hierarchical"/&gt;
 *             &lt;enumeration value="hierarchical-parent"/&gt;
 *             &lt;enumeration value="hierarchical-child"/&gt;
 *             &lt;enumeration value="temporal"/&gt;
 *             &lt;enumeration value="temporal-earlier"/&gt;
 *             &lt;enumeration value="temporal-later"/&gt;
 *             &lt;enumeration value="family"/&gt;
 *             &lt;enumeration value="associative"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cpfRelation")
public class CpfRelation
    extends MRelationBody
{

    @XmlAttribute(name = "cpfRelationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cpfRelationType;

    /**
     * Gets the value of the cpfRelationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpfRelationType() {
        return cpfRelationType;
    }

    /**
     * Sets the value of the cpfRelationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpfRelationType(String value) {
        this.cpfRelationType = value;
    }

}
