//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 12:52:00 PM CET 
//


package eu.apenet.dpt.utils.eaccpf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.apenet.dpt.utils.eaccpf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.apenet.dpt.utils.eaccpf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link EacCpf }
     * 
     */
    public EacCpf createEacCpf() {
        return new EacCpf();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link CpfDescription }
     * 
     */
    public CpfDescription createCpfDescription() {
        return new CpfDescription();
    }

    /**
     * Create an instance of {@link MultipleIdentities }
     * 
     */
    public MultipleIdentities createMultipleIdentities() {
        return new MultipleIdentities();
    }

    /**
     * Create an instance of {@link RecordId }
     * 
     */
    public RecordId createRecordId() {
        return new RecordId();
    }

    /**
     * Create an instance of {@link OtherRecordId }
     * 
     */
    public OtherRecordId createOtherRecordId() {
        return new OtherRecordId();
    }

    /**
     * Create an instance of {@link MaintenanceStatus }
     * 
     */
    public MaintenanceStatus createMaintenanceStatus() {
        return new MaintenanceStatus();
    }

    /**
     * Create an instance of {@link PublicationStatus }
     * 
     */
    public PublicationStatus createPublicationStatus() {
        return new PublicationStatus();
    }

    /**
     * Create an instance of {@link MaintenanceAgency }
     * 
     */
    public MaintenanceAgency createMaintenanceAgency() {
        return new MaintenanceAgency();
    }

    /**
     * Create an instance of {@link AgencyCode }
     * 
     */
    public AgencyCode createAgencyCode() {
        return new AgencyCode();
    }

    /**
     * Create an instance of {@link OtherAgencyCode }
     * 
     */
    public OtherAgencyCode createOtherAgencyCode() {
        return new OtherAgencyCode();
    }

    /**
     * Create an instance of {@link AgencyName }
     * 
     */
    public AgencyName createAgencyName() {
        return new AgencyName();
    }

    /**
     * Create an instance of {@link MaintenanceHistory }
     * 
     */
    public MaintenanceHistory createMaintenanceHistory() {
        return new MaintenanceHistory();
    }

    /**
     * Create an instance of {@link MaintenanceEvent }
     * 
     */
    public MaintenanceEvent createMaintenanceEvent() {
        return new MaintenanceEvent();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link EventDateTime }
     * 
     */
    public EventDateTime createEventDateTime() {
        return new EventDateTime();
    }

    /**
     * Create an instance of {@link AgentType }
     * 
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link EventDescription }
     * 
     */
    public EventDescription createEventDescription() {
        return new EventDescription();
    }

    /**
     * Create an instance of {@link LanguageDeclaration }
     * 
     */
    public LanguageDeclaration createLanguageDeclaration() {
        return new LanguageDeclaration();
    }

    /**
     * Create an instance of {@link ConventionDeclaration }
     * 
     */
    public ConventionDeclaration createConventionDeclaration() {
        return new ConventionDeclaration();
    }

    /**
     * Create an instance of {@link LocalTypeDeclaration }
     * 
     */
    public LocalTypeDeclaration createLocalTypeDeclaration() {
        return new LocalTypeDeclaration();
    }

    /**
     * Create an instance of {@link Abbreviation }
     * 
     */
    public Abbreviation createAbbreviation() {
        return new Abbreviation();
    }

    /**
     * Create an instance of {@link LocalControl }
     * 
     */
    public LocalControl createLocalControl() {
        return new LocalControl();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link SourceEntry }
     * 
     */
    public SourceEntry createSourceEntry() {
        return new SourceEntry();
    }

    /**
     * Create an instance of {@link EntityId }
     * 
     */
    public EntityId createEntityId() {
        return new EntityId();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link UseDates }
     * 
     */
    public UseDates createUseDates() {
        return new UseDates();
    }

    /**
     * Create an instance of {@link NameEntryParallel }
     * 
     */
    public NameEntryParallel createNameEntryParallel() {
        return new NameEntryParallel();
    }

    /**
     * Create an instance of {@link eu.apenet.dpt.utils.eaccpf.NameEntry }
     * 
     */
    public eu.apenet.dpt.utils.eaccpf.NameEntry createNameEntry() {
        return new eu.apenet.dpt.utils.eaccpf.NameEntry();
    }

    /**
     * Create an instance of {@link PreferredForm }
     * 
     */
    public PreferredForm createPreferredForm() {
        return new PreferredForm();
    }

    /**
     * Create an instance of {@link AuthorizedForm }
     * 
     */
    public AuthorizedForm createAuthorizedForm() {
        return new AuthorizedForm();
    }

    /**
     * Create an instance of {@link AlternativeForm }
     * 
     */
    public AlternativeForm createAlternativeForm() {
        return new AlternativeForm();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link ExistDates }
     * 
     */
    public ExistDates createExistDates() {
        return new ExistDates();
    }

    /**
     * Create an instance of {@link Places }
     * 
     */
    public Places createPlaces() {
        return new Places();
    }

    /**
     * Create an instance of {@link LocalDescriptions }
     * 
     */
    public LocalDescriptions createLocalDescriptions() {
        return new LocalDescriptions();
    }

    /**
     * Create an instance of {@link LanguagesUsed }
     * 
     */
    public LanguagesUsed createLanguagesUsed() {
        return new LanguagesUsed();
    }

    /**
     * Create an instance of {@link LegalStatuses }
     * 
     */
    public LegalStatuses createLegalStatuses() {
        return new LegalStatuses();
    }

    /**
     * Create an instance of {@link Occupations }
     * 
     */
    public Occupations createOccupations() {
        return new Occupations();
    }

    /**
     * Create an instance of {@link Functions }
     * 
     */
    public Functions createFunctions() {
        return new Functions();
    }

    /**
     * Create an instance of {@link Mandates }
     * 
     */
    public Mandates createMandates() {
        return new Mandates();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddressLine }
     * 
     */
    public AddressLine createAddressLine() {
        return new AddressLine();
    }

    /**
     * Create an instance of {@link PlaceEntry }
     * 
     */
    public PlaceEntry createPlaceEntry() {
        return new PlaceEntry();
    }

    /**
     * Create an instance of {@link LocalDescription }
     * 
     */
    public LocalDescription createLocalDescription() {
        return new LocalDescription();
    }

    /**
     * Create an instance of {@link LanguageUsed }
     * 
     */
    public LanguageUsed createLanguageUsed() {
        return new LanguageUsed();
    }

    /**
     * Create an instance of {@link LegalStatus }
     * 
     */
    public LegalStatus createLegalStatus() {
        return new LegalStatus();
    }

    /**
     * Create an instance of {@link Occupation }
     * 
     */
    public Occupation createOccupation() {
        return new Occupation();
    }

    /**
     * Create an instance of {@link Function }
     * 
     */
    public Function createFunction() {
        return new Function();
    }

    /**
     * Create an instance of {@link Mandate }
     * 
     */
    public Mandate createMandate() {
        return new Mandate();
    }

    /**
     * Create an instance of {@link MSimpleDescription }
     * 
     */
    public MSimpleDescription createMSimpleDescription() {
        return new MSimpleDescription();
    }

    /**
     * Create an instance of {@link PlaceRole }
     * 
     */
    public PlaceRole createPlaceRole() {
        return new PlaceRole();
    }

    /**
     * Create an instance of {@link StructureOrGenealogy }
     * 
     */
    public StructureOrGenealogy createStructureOrGenealogy() {
        return new StructureOrGenealogy();
    }

    /**
     * Create an instance of {@link GeneralContext }
     * 
     */
    public GeneralContext createGeneralContext() {
        return new GeneralContext();
    }

    /**
     * Create an instance of {@link BiogHist }
     * 
     */
    public BiogHist createBiogHist() {
        return new BiogHist();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Relations }
     * 
     */
    public Relations createRelations() {
        return new Relations();
    }

    /**
     * Create an instance of {@link RelationEntry }
     * 
     */
    public RelationEntry createRelationEntry() {
        return new RelationEntry();
    }

    /**
     * Create an instance of {@link ObjectXMLWrap }
     * 
     */
    public ObjectXMLWrap createObjectXMLWrap() {
        return new ObjectXMLWrap();
    }

    /**
     * Create an instance of {@link ObjectBinWrap }
     * 
     */
    public ObjectBinWrap createObjectBinWrap() {
        return new ObjectBinWrap();
    }

    /**
     * Create an instance of {@link MRelationBody }
     * 
     */
    public MRelationBody createMRelationBody() {
        return new MRelationBody();
    }

    /**
     * Create an instance of {@link CpfRelation }
     * 
     */
    public CpfRelation createCpfRelation() {
        return new CpfRelation();
    }

    /**
     * Create an instance of {@link ResourceRelation }
     * 
     */
    public ResourceRelation createResourceRelation() {
        return new ResourceRelation();
    }

    /**
     * Create an instance of {@link FunctionRelation }
     * 
     */
    public FunctionRelation createFunctionRelation() {
        return new FunctionRelation();
    }

    /**
     * Create an instance of {@link AlternativeSet }
     * 
     */
    public AlternativeSet createAlternativeSet() {
        return new AlternativeSet();
    }

    /**
     * Create an instance of {@link SetComponent }
     * 
     */
    public SetComponent createSetComponent() {
        return new SetComponent();
    }

    /**
     * Create an instance of {@link ComponentEntry }
     * 
     */
    public ComponentEntry createComponentEntry() {
        return new ComponentEntry();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link DateRange }
     * 
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link FromDate }
     * 
     */
    public FromDate createFromDate() {
        return new FromDate();
    }

    /**
     * Create an instance of {@link ToDate }
     * 
     */
    public ToDate createToDate() {
        return new ToDate();
    }

    /**
     * Create an instance of {@link DateSet }
     * 
     */
    public DateSet createDateSet() {
        return new DateSet();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link DescriptiveNote }
     * 
     */
    public DescriptiveNote createDescriptiveNote() {
        return new DescriptiveNote();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link MMixedContent }
     * 
     */
    public MMixedContent createMMixedContent() {
        return new MMixedContent();
    }

    /**
     * Create an instance of {@link ChronList }
     * 
     */
    public ChronList createChronList() {
        return new ChronList();
    }

    /**
     * Create an instance of {@link ChronItem }
     * 
     */
    public ChronItem createChronItem() {
        return new ChronItem();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Outline }
     * 
     */
    public Outline createOutline() {
        return new Outline();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link Span }
     * 
     */
    public Span createSpan() {
        return new Span();
    }

    /**
     * Create an instance of {@link Identity.NameEntry }
     * 
     */
    public Identity.NameEntry createIdentityNameEntry() {
        return new Identity.NameEntry();
    }

}
