//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.01 at 03:56:00 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:isbn:1-931666-33-4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.apenet.dpt.utils.eaccpf;
