//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 12:52:00 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:isbn:1-931666-33-4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.apenet.dpt.utils.eaccpf;
