//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.17 at 08:52:22 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.archivesportaleurope.eu/profiles/eag/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.apenet.dpt.standalone.gui.eag2012.data;