//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.17 at 08:52:22 AM CEST 
//


package eu.apenet.dpt.standalone.gui.eag2012.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}descriptiveNote" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}contact" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}webpage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}microformser" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}photographser" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}digitalser" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}photocopyser" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.archivesportaleurope.eu/profiles/eag/}question"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descriptiveNote",
    "contact",
    "webpage",
    "microformser",
    "photographser",
    "digitalser",
    "photocopyser"
})
@XmlRootElement(name = "reproductionser")
public class Reproductionser {

    protected DescriptiveNote descriptiveNote;
    protected Contact contact;
    protected List<Webpage> webpage;
    protected Microformser microformser;
    protected Photographser photographser;
    protected Digitalser digitalser;
    protected Photocopyser photocopyser;
    @XmlAttribute(name = "question", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String question;

    /**
     * Gets the value of the descriptiveNote property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveNote }
     *     
     */
    public DescriptiveNote getDescriptiveNote() {
        return descriptiveNote;
    }

    /**
     * Sets the value of the descriptiveNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveNote }
     *     
     */
    public void setDescriptiveNote(DescriptiveNote value) {
        this.descriptiveNote = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setContact(Contact value) {
        this.contact = value;
    }

    /**
     * Gets the value of the webpage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the webpage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWebpage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Webpage }
     * 
     * 
     */
    public List<Webpage> getWebpage() {
        if (webpage == null) {
            webpage = new ArrayList<Webpage>();
        }
        return this.webpage;
    }

    /**
     * Gets the value of the microformser property.
     * 
     * @return
     *     possible object is
     *     {@link Microformser }
     *     
     */
    public Microformser getMicroformser() {
        return microformser;
    }

    /**
     * Sets the value of the microformser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Microformser }
     *     
     */
    public void setMicroformser(Microformser value) {
        this.microformser = value;
    }

    /**
     * Gets the value of the photographser property.
     * 
     * @return
     *     possible object is
     *     {@link Photographser }
     *     
     */
    public Photographser getPhotographser() {
        return photographser;
    }

    /**
     * Sets the value of the photographser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Photographser }
     *     
     */
    public void setPhotographser(Photographser value) {
        this.photographser = value;
    }

    /**
     * Gets the value of the digitalser property.
     * 
     * @return
     *     possible object is
     *     {@link Digitalser }
     *     
     */
    public Digitalser getDigitalser() {
        return digitalser;
    }

    /**
     * Sets the value of the digitalser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Digitalser }
     *     
     */
    public void setDigitalser(Digitalser value) {
        this.digitalser = value;
    }

    /**
     * Gets the value of the photocopyser property.
     * 
     * @return
     *     possible object is
     *     {@link Photocopyser }
     *     
     */
    public Photocopyser getPhotocopyser() {
        return photocopyser;
    }

    /**
     * Sets the value of the photocopyser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Photocopyser }
     *     
     */
    public void setPhotocopyser(Photocopyser value) {
        this.photocopyser = value;
    }

    /**
     * Gets the value of the question property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestion() {
        return question;
    }

    /**
     * Sets the value of the question property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestion(String value) {
        this.question = value;
    }

}
