//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.17 at 08:52:22 AM CEST 
//


package eu.apenet.dpt.utils.eag2012;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}searchroom"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}library" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}internetAccess" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}techservices" minOccurs="0"/>
 *         &lt;element ref="{http://www.archivesportaleurope.eu/profiles/eag/}recreationalServices" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchroom",
    "library",
    "internetAccess",
    "techservices",
    "recreationalServices"
})
@XmlRootElement(name = "services")
public class Services {

    @XmlElement(required = true)
    protected Searchroom searchroom;
    protected Library library;
    protected InternetAccess internetAccess;
    protected Techservices techservices;
    protected RecreationalServices recreationalServices;

    /**
     * Gets the value of the searchroom property.
     * 
     * @return
     *     possible object is
     *     {@link Searchroom }
     *     
     */
    public Searchroom getSearchroom() {
        return searchroom;
    }

    /**
     * Sets the value of the searchroom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Searchroom }
     *     
     */
    public void setSearchroom(Searchroom value) {
        this.searchroom = value;
    }

    /**
     * Gets the value of the library property.
     * 
     * @return
     *     possible object is
     *     {@link Library }
     *     
     */
    public Library getLibrary() {
        return library;
    }

    /**
     * Sets the value of the library property.
     * 
     * @param value
     *     allowed object is
     *     {@link Library }
     *     
     */
    public void setLibrary(Library value) {
        this.library = value;
    }

    /**
     * Gets the value of the internetAccess property.
     * 
     * @return
     *     possible object is
     *     {@link InternetAccess }
     *     
     */
    public InternetAccess getInternetAccess() {
        return internetAccess;
    }

    /**
     * Sets the value of the internetAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternetAccess }
     *     
     */
    public void setInternetAccess(InternetAccess value) {
        this.internetAccess = value;
    }

    /**
     * Gets the value of the techservices property.
     * 
     * @return
     *     possible object is
     *     {@link Techservices }
     *     
     */
    public Techservices getTechservices() {
        return techservices;
    }

    /**
     * Sets the value of the techservices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Techservices }
     *     
     */
    public void setTechservices(Techservices value) {
        this.techservices = value;
    }

    /**
     * Gets the value of the recreationalServices property.
     * 
     * @return
     *     possible object is
     *     {@link RecreationalServices }
     *     
     */
    public RecreationalServices getRecreationalServices() {
        return recreationalServices;
    }

    /**
     * Sets the value of the recreationalServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecreationalServices }
     *     
     */
    public void setRecreationalServices(RecreationalServices value) {
        this.recreationalServices = value;
    }

}
